# Generated by Django 4.2.9 on 2024-01-25 08:38

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("myfile", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="yourmodel",
            name="name",
        ),
        migrations.AlterField(
            model_name="yourmodel",
            name="file_upload",
            field=models.FileField(
                default=None, max_length=250, null=True, upload_to="uploads/"
            ),
        ),
    ]
