# Generated by Django 4.2.9 on 2024-01-25 08:51

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("myfile", "0002_remove_yourmodel_name_alter_yourmodel_file_upload"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="YourModel",
            new_name="uploadfile",
        ),
    ]
